test: &default

  # Credentials for REST APIs
  client_id: <%= ENV["PP_CLIENT_ID"] %>
  client_secret: <%= ENV["PP_CLIENT_SECRET"] %>

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: <%= ENV["PP_APP_ID"] %>
  username: <%= ENV["PP_USERNAME"] %>
  password: <%= ENV["PP_PASSWORD"] %>
  signature: <%= ENV["PP_SIGNATURE"] %>
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: <%= ENV["PP_SANDBOX_EMAIL_ADDRESS"] %>

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
